apiVersion: v2
name: autocert
version: 1.20.4
appVersion: 0.20.3
description: A kubernetes add-on that automatically injects TLS/HTTPS certificates into your containers.
keywords:
 - ca
 - tls
 - pki
 - x509
 - step
 - step-ca
 - step-certificates
 - smallstep
 - certificate
 - certificates
 - authority
 - security
 - security-tools
 - certificate-authority
 - kubernetes
home: https://smallstep.com
icon: https://raw.githubusercontent.com/smallstep/autocert/master/icon.png
sources:
 - https://github.com/smallstep/autocert
maintainers:
 - name: Mariano Cano
   email: mariano@smallstep.com
dependencies:
  - name: step-certificates
    version: 1.29.0
    repository: https://smallstep.github.io/helm-charts
    condition: step-certificates.enabled
    tags:
      - step-certificates
