apiVersion: v2
name: step-issuer
type: application
version: 1.9.7
appVersion: 0.9.7
description: Step-issuer helm chart for kubernetes.
home: https://smallstep.com
keywords:
 - authority
 - ca
 - cert-manager
 - certificate
 - certificate-authority
 - certificates
 - kubernetes
 - pki
 - security
 - security-tools
 - smallstep
 - ssh
 - step
 - step-ca
 - step-issuer
 - tls
 - x509
maintainers:
  - name: Mariano Cano
    email: mariano@smallstep.com
  - name: Irwan Shofwan
    email: abigaelse2@gmail.com
  - name: Muhammad Fauzan Razandi
    email: muhammad.fauzan.razandi.16@gmail.com
