{{- if .Release.IsInstall -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "step-certificates.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "step-certificates.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "step-certificates.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "step-certificates.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "step-certificates.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "step-certificates.fullname" . }}-config
  apiGroup: rbac.authorization.k8s.io
---
{{ if .Values.autocert.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "step-certificates.fullname" . }}-config
  labels:
    {{- include "step-certificates.labels" . | nindent 4 }}
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "step-certificates.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "step-certificates.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "step-certificates.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "step-certificates.fullname" . }}-config
  apiGroup: rbac.authorization.k8s.io
{{- end }} # if .Values.autocert.enabled
{{- end }}
