# Secrets that will be updated by the configuration job: 
# 1. CA keys password.
# 2. Provisioner password.

{{- if or .Values.bootstrap.secrets .Values.inject.enabled }}
apiVersion: v1
kind: Secret
type: smallstep.com/ca-password
metadata:
  name: {{ include "step-certificates.fullname" . }}-ca-password
  namespace: {{ .Release.Namespace }}
{{- if .Values.inject.enabled }}
data:
  password: {{ .Values.inject.secrets.ca_password }}
{{- end }}
{{- end }}
---
{{- if or .Values.bootstrap.secrets .Values.inject.enabled }}
apiVersion: v1
kind: Secret
type: smallstep.com/provisioner-password
metadata:
  name: {{ include "step-certificates.fullname" . }}-provisioner-password
  namespace: {{ .Release.Namespace }}
{{- if .Values.inject.enabled }}
data:
  password: {{ .Values.inject.secrets.provisioner_password }}
{{- end }}
{{- end }}
---
{{- if .Values.inject.enabled }}
apiVersion: v1
kind: Secret
type: smallstep.com/private-keys
metadata:
  name: {{ include "step-certificates.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  intermediate_ca_key: |-
    {{- .Values.inject.secrets.x509.intermediate_ca_key  | nindent 4 }}
  root_ca_key: |-
    {{- .Values.inject.secrets.x509.root_ca_key | nindent 4 }}
  ssh_host_ca_key: |-
    {{- .Values.inject.secrets.ssh.host_ca_key | nindent 4 }}
  ssh_user_ca_key: |-
    {{- .Values.inject.secrets.ssh.user_ca_key | nindent 4 }}
{{- end }}