# Secrets that will be updated by the configuration job: 
# 1. CA keys password.
# 2. Provisioner password.

{{- if or (and .Values.bootstrap.enabled .Values.bootstrap.secrets) (and .Values.inject.enabled (not (eq .Values.inject.secrets.ca_password ""))) }}
apiVersion: v1
kind: Secret
{{- if .Values.inject.enabled }}
type: smallstep.com/ca-password
{{- end }}
metadata:
  name: {{ include "step-certificates.fullname" . }}-ca-password
  namespace: {{ .Release.Namespace }}
{{- if .Values.inject.enabled }}
data:
  password: {{ .Values.inject.secrets.ca_password }}
{{- end }}
{{- end }}
---
{{- if or (and .Values.bootstrap.enabled .Values.bootstrap.secrets) (and .Values.inject.enabled (not (eq .Values.inject.secrets.provisioner_password ""))) }}
apiVersion: v1
kind: Secret
{{- if .Values.inject.enabled }}
type: smallstep.com/provisioner-password
{{- end }}
metadata:
  name: {{ include "step-certificates.fullname" . }}-provisioner-password
  namespace: {{ .Release.Namespace }}
{{- if .Values.inject.enabled }}
data:
  password: {{ .Values.inject.secrets.provisioner_password }}
{{- end }}
{{- end }}
---
{{- if and .Values.inject.enabled (and .Values.inject.secrets.certificate_issuer.enabled (not (eq .Values.inject.secrets.certificate_issuer.password ""))) }}
apiVersion: v1
kind: Secret
type: smallstep.com/certificate-issuer-password
metadata:
  name: {{ include "step-certificates.fullname" . }}-certificate-issuer-password
  namespace: {{ .Release.Namespace }}
data:
  password: {{ .Values.inject.secrets.certificate_issuer.password }}
{{- end }}
---
{{- if and .Values.inject.enabled (and .Values.inject.secrets.ssh.enabled (not (eq .Values.inject.secrets.ssh.host_ca_password ""))) }}
apiVersion: v1
kind: Secret
type: smallstep.com/ssh-host-ca-password
metadata:
  name: {{ include "step-certificates.fullname" . }}-ssh-host-ca-password
  namespace: {{ .Release.Namespace }}
data:
  password: {{ .Values.inject.secrets.ssh.host_ca_password }}
{{- end }}
---
{{- if and .Values.inject.enabled (and .Values.inject.secrets.ssh.enabled (not (eq .Values.inject.secrets.ssh.user_ca_password ""))) }}
apiVersion: v1
kind: Secret
type: smallstep.com/ssh-user-ca-password
metadata:
  name: {{ include "step-certificates.fullname" . }}-ssh-user-ca-password
  namespace: {{ .Release.Namespace }}
data:
  password: {{ .Values.inject.secrets.ssh.user_ca_password }}
{{- end }}
---
{{- if and .Values.inject.enabled .Values.bootstrap.secrets}}
apiVersion: v1
kind: Secret
type: smallstep.com/private-keys
metadata:
  name: {{ include "step-certificates.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if and .Values.inject.secrets.certificate_issuer.enabled (not (eq .Values.inject.secrets.certificate_issuer.key "")) }}
  certificate_issuer_key: |-
    {{- .Values.inject.secrets.certificate_issuer.key | nindent 4 }}
  {{- end }}
  {{- if .Values.inject.secrets.x509.enabled }}
  intermediate_ca_key: |-
    {{- .Values.inject.secrets.x509.intermediate_ca_key  | nindent 4 }}
  root_ca_key: |-
    {{- .Values.inject.secrets.x509.root_ca_key | nindent 4 }}
  {{- end }}
  {{- if .Values.inject.secrets.ssh.enabled }}
  {{- if not (eq "" .Values.inject.secrets.ssh.host_ca_key) }}
  ssh_host_ca_key: |-
    {{- .Values.inject.secrets.ssh.host_ca_key | nindent 4 }}
  {{- end }}
  {{- if not (eq "" .Values.inject.secrets.ssh.user_ca_key) }}
  ssh_user_ca_key: |-
    {{- .Values.inject.secrets.ssh.user_ca_key | nindent 4 }}
  {{- end }}
  {{- end}}
{{- end }}
---
{{- if .Values.linkedca.token }}
apiVersion: v1
kind: Secret
type: smallstep.com/step-ca-token
metadata:
  name: {{ include "step-certificates.fullname" . }}-step-ca-token
  namespace: {{ .Release.Namespace }}
data:
  token: {{ .Values.linkedca.token }}
{{- end }}
